# MD033/no-inline-html: Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/v0.27.0/doc/md033.md
# we want to allow inline-html to be able to support github details accordion feature
MD033: false

# https://github.com/DavidAnson/markdownlint/blob/v0.27.0/doc/md013.md
# the width that github supports for markdown files
MD013:
  line_length: 180

# https://github.com/DavidAnson/markdownlint/blob/v0.27.0/doc/md023.md
# to support heading nested inside detail block accordions
MD023: false
