# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: rw-azure-deploy-rg-and-stg

on:
  workflow_call:
    inputs:
      resource-group-name:
        description: The name of the resource group that the storage account will be placed into
        required: true
        type: string
      storage-account-prefix:
        description: The prefix of the storage account
        default: storage
        required: false
        type: string
      location:
        description: The azure location/region to deploy the resources into
        default: westus3
        required: false
        type: string
      runs-on:
        required: false
        default: '["ubuntu-latest"]'
        type: string
    secrets:
      tenant-id:
        description: The azure tenant id you are deploying to
        required: true
      subscription-id:
        description: Your azure subscription id
        required: true
      client-id:
        description: The Azure Service Principal id with access to deploy to your subscription
        required: true
      client-secret:
        description: The Azure Service Principal password with access to deploy to your subscription
        required: true

jobs:
  rw-azure-deploy-rg-and-stg:
    name: reusable workflow that deploys a resource group with a storage account in it
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: check clone
        run: |
          pwd
          ls -al

      # note: can put in things like validation actions here

      # Log into Azure
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.client-id }}","clientSecret":"${{ secrets.client-secret }}","subscriptionId":"${{ secrets.subscription-id }}","tenantId":"${{ secrets.tenant-id }}"}'
          enable-AzPSSession: true

      - name: pwsh az check connection
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
            Get-AzResourceGroup
          azPSVersion: latest

      - name: deploy azure resource group to subscription
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ inputs.location }}
          subscriptionId: ${{ secrets.subscription-id }}
          template: main.bicep
          parameters: "location=${{ inputs.location }} resourceGroupName=${{ inputs.resource-group-name }}"
          failOnStdErr: true

      - name: deploy azure storage account to resource group
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.subscription-id }}
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: storage.bicep
          parameters: "location=${{ inputs.location }} namePrefix=${{ inputs.storage-account-prefix }}"
          deploymentMode: Complete
          failOnStdErr: true
