# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: rw-hello-world

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  rw-hello-world:
    name: reusable workflow hello world
    runs-on: ${{ inputs.RUNS_ON }}
    # runs-on: ubuntu-latest

    steps:
      - name: run GitHub Action from a GitHub Repo
        # https://github.com/JasonCubic/ga-hello-world
        uses: JasonCubic/ga-hello-world@main
